### ISSUE TITLE
No module named 'gensim.summarization'

### ISSUE THREAD

**Issue by Ahmed-Naseer-01** [Amey-Thakur/TEXT-SUMMARIZER#2]
from gensim.summarization import summarize
ModuleNotFoundError: No module named 'gensim.summarization'
kindly tell how to fix it

**Comment by Amey-Thakur** [comment]
To fix the error "ModuleNotFoundError: No module named 'gensim.summarization'", install the gensim library using pip: 
```pip install gensim```

Note: I'm not actively working on the project, but this should resolve the issue.
